# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f19c03ea882ea1b357ec98e473d648a0192ba52f02d395427b6c9589efe661551df4156dec2f826670a966bcb099e43ea23a330ff0089d0e0e8936c5e4bdbde1

test:
  secret_key_base: e60fe2d9294d135a287a75684045497dbf8b5363f68cae946e669460c2c5bb8147cc1c49b6642613c3f99a0147bd5ef1897d7e3f7af27d2a66b291ba84dd58a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
